worldcoin/world-id-docs

docs/feedback.md
docs/index.md

feat: add feedback page

---

src/pages/api-docs/reference.mdx

refactor: update reference page

---

src/components/Cta.tsx
src/components/UseCasesList.tsx

Lead to https://worldcoin.org/grants

chore: add grants urls

---

src/components/Navigation.tsx
src/pages/api-docs/sign-in-reference.mdx

@0xPenryn this is the PR we were working on in Tokyo, can you take it on? CC @maxpetretta

feat: sign in with worldcoin docs

---

src/pages/id/sign-in.mdx

Fixes a lot of broken links in the sign-in documentation

fix: update links in sign-in.mdx

---

src/pages/idkit/reference.mdx

Blocked by https://github.com/worldcoin/idkit-js/pull/120

Add SignInButton to docs

---

src/pages/advanced/on-chain.mdx

updates docs to use the router addresses, and explains to use groupId 1 for Orb and groupId 0 for Phone

chore: Router addresses

---

src/pages/further-reading/oidc.mdx
src/pages/id/sign-in.mdx
src/pages/reference/sign-in.mdx

documents the `scope` param, clarifies `nonce` requirement for implicit flow, recommends good practices, and other general improvements

chore: improve OIDC docs

---

src/pages/reference/address-book.mdx

updates a couple contract addresses and removes phone on bridged chains

chore: update addressbook

---

cspell.json
mdx/rehype.mjs
src/components/mdx.tsx
src/pages/reference/address-book.mdx
src/pages/reference/api.mdx
src/pages/reference/contracts.mdx
src/pages/reference/idkit.mdx
typography.js

updates reference section of documentation for idkit v1

feat: reference section updates

---

cspell.json
src/pages/reference/address-book.mdx

Updates address book to reflect sepolia migration

feat: sepolia testnet

---

src/components/Header.tsx
src/components/Layout.tsx

fixes navbar moving when overscrolling. now navbar location is fixed

fix: navbar position when overscrolling

---

next.config.mjs

updates redirects to account for changes to the structure
completes wid-810

chore: update redirects

---

src/components/Navigation.tsx

fixes sign in reference missing from nav
completes wid-812

fix: add sign in reference to nav

---

src/pages/reference/address-book.mdx

updates eth sepolia identity manager address

fix: eth sepolia id manager address

---

src/pages/id/cloud.mdx
src/pages/quick-start/configuration.mdx
src/pages/reference/api.mdx
src/pages/reference/idkit.mdx

updates the documentation to reflect changes made to IDKit and the Developer Portal to support the signal_hash when verifying cloud proofs.

feat: api v2, idkit v1.2 docs

---

pnpm-lock.yaml
src/pages/api/action/index.ts
src/pages/id/cloud.mdx
src/pages/reference/idkit.mdx
src/pages/try.tsx

Updates "Try It Out" page to create actions on-the-fly, accounting for the removal of dynamic actions from the developer portal.
Do not merge until tested (pending Dev Portal fix).

feat: on-the-fly action creation

---

src/components/Navigation.tsx
src/components/Toggle.tsx

https://github.com/worldcoin/world-id-docs/assets/89008845/529e0f1f-62a1-47d3-8acd-25a2c8f26827

animate toggle

---

src/components/Navigation.tsx
src/pages/mini-apps/commands/verify.mdx
src/pages/mini-apps/quick-start/publishing.mdx
src/pages/mini-apps/reference/api.mdx
src/pages/mini-apps/reference/errors.mdx
src/pages/mini-apps/reference/sharing.mdx

Add the technical reference section to the docs.
This includes the verify, pay, and walletAuth

Feat: Mini kit Technical Reference

---

pnpm-lock.yaml
src/components/Navigation.tsx
src/pages/id/libraries.mdx
src/pages/quick-start/installation.mdx

We will officially support idkit-rs and swift now since we have some partners using them. Kotlin coming soon via swift

Expose idkit rs and swift officially

---

src/pages/reference/address-book.mdx

updates address book to reflect new Sepolia identity manager

feat: update sepolia identity manager

---

src/pages/sign-in/index.mdx

Add a disclaimer if apps are mobile to not use sign in.

Disclaimer for sign in

---

src/pages/id/libraries.mdx

Add Idkit Kotlin 

---

next.config.mjs

fix redirects

---

src/pages/api/auth/index.ts
src/pages/world-id/reference/sign-in.mdx

fix sign in

---

cspell.json
package.json
pnpm-lock.yaml
src/components/QrTest.tsx
src/pages/mini-apps/quick-start/testing.mdx

Open App Store

---

src/pages/world-chain/developers/deploy.mdx

This pull request addresses issues in the "Deploy on World Chain" section of the documentation by updating the instructions to fix compilation errors and providing a new testing flow for the `HelloWorldChain` contract.
The original documentation outlined the following steps:
1. **Initialize a Foundry Project** : 
- Run the command:
```bash
forge init hello-world-chain && cd hello-world-chain
```
Skipping to Compiling the contract
3. **Compile the Contract** : 
- Users were instructed to run:
```bash
forge build
```
- However, this resulted in the following compilation errors:
```arduino
Compiler run failed:
Error (6275): Source "src/Counter.sol" not found: File not found. Searched the following locations: "/Users/billy/Documents/Code/Reclaim/world-coin/hello-world-chain".
ParserError: …
```

Fix "Deploy on World Chain" Documentation to Resolve Compilation Errors and Update Test Flow

---

src/pages/mini-apps/commands/pay.mdx
src/pages/mini-apps/commands/send-transaction.mdx
src/pages/mini-apps/reference/api.mdx

transactions and remove optimism

more docs improvements

---

src/pages/mini-apps/quick-start/installing.mdx

update install docs

---

src/pages/mini-apps/commands/wallet-auth.mdx

Remove outdated message

---

src/pages/mini-apps/commands/wallet-auth.mdx

Remove disclaimer note

---

src/pages/mini-apps/quick-start/installing.mdx

remove old template

---

cspell.json
public/code/world-chain-sepolia/testnet_rollup.json
public/code/world-chain/rollup.json
src/components/Navigation.tsx
src/pages/world-chain/developers/world-chain-contracts.mdx
src/pages/world-chain/reference/address-book.mdx
src/pages/world-chain/reference/node-setup.mdx
src/pages/world-id/reference/address-book.mdx

- Add World Chain node setup guide
- Migrate Blockscout links to Worldscan

Add World Chain node setup guide

---

src/pages/mini-apps/reference/sharing.mdx

Reverts worldcoin/world-id-docs#324

Revert "update sharing"

---

src/pages/mini-apps/commands/send-transaction.mdx
src/pages/mini-apps/reference/errors.mdx

Tx error docs

---

src/pages/world-chain/developers/template.mdx

Link to address book is incorrect on this page: https://docs.world.org/world-chain/developers/template

fix: incorrect URL for address book

---

src/components/Navigation.tsx
src/pages/mini-apps/commands/notifications.mdx
src/pages/mini-apps/commands/send-notifications.mdx
src/pages/mini-apps/commands/share-contacts.mdx
src/pages/mini-apps/commands/share-social-graph.mdx
src/pages/mini-apps/quick-start/commands.mdx
src/pages/mini-apps/reference/api.mdx

notifications and contacts docs

Notifications and contacts docs

---

src/pages/mini-apps/commands/send-notifications.mdx
src/pages/mini-apps/commands/share-contacts.mdx

Update Min app version

---

src/pages/mini-apps/reference/api.mdx

Add Path example

---

src/pages/world-id/id/cloud.mdx
src/pages/world-id/quick-start/installation.mdx

Make the docs more easy to understand by minimizing incognito action verbiage and emphasize just verify with world id

Improve understandability of docs

---

src/pages/mini-apps/commands/send-notifications.mdx

Fix notifications docs. Accidentally copied share contacts into the send notifications section

Fix notifications docs

---

src/pages/mini-apps/commands/send-transaction.mdx

Update transaction docs

---

src/pages/mini-apps/reference/api.mdx

Add AppID to the send notification in docs forgot to add this

Add app id to the transactions

---

src/pages/mini-apps/commands/send-notifications.mdx

Fix send notifications

---

src/pages/world-chain/providers/nodes.mdx
src/pages/world-chain/reference/node-setup.mdx

Adds information on QuickNode discounts for World Chain devs. Updates node guide env vars to align with simple-worldchain-node.

Quicknode and node guide env var updates

---

.github/workflows/ci.yml

fix: set runner to 24.04

---

src/pages/mini-apps/commands/send-transaction.mdx

send eth support

---

src/pages/mini-apps/commands/send-transaction.mdx

add comment

---

src/pages/world-id/index.mdx

Been more than 1 year now. Time to remove the announce

Remove old announce

---

src/components/Navigation.tsx
src/pages/mini-apps/sharing/quick-actions.mdx

Quick actions is not clear it's sharing too

specify sharing

---

.cursor/rules/docs-format.mdc
cspell.json
llms.txt
public/llms-full.txt
public/llms.txt

Next step is to be listed on the llms.txt marketplaces, but right now devs can access it in docs.world.org/llms-full.txt

Adding LLMs.txt for AI promt optimization

---

src/components/Navigation.tsx
src/pages/mini-apps/commands/get-permissions.mdx
src/pages/mini-apps/quick-start/commands.mdx

Get permissions command

---

src/components/Navigation.tsx
src/pages/mini-apps/commands/send-haptic-feedback.mdx
src/pages/mini-apps/quick-start/commands.mdx

New command, not yet implemented

Add docs for haptics

---

src/components/SageSupportLinkWizard.tsx
src/pages/mini-apps/sharing/sage-qa.mdx

- added Sage Support Link creation wizard component
- added documentation for Sage Support Link

Added Sage Support Link

---

public/llms-full.txt
src/pages/world-chain/index.mdx
src/pages/world-chain/quick-start/fund-wallet.mdx
src/pages/world-chain/quick-start/why.mdx
src/pages/world-chain/reference/node-setup.mdx

Hi y'all - Brad from OP Labs here! We've done some larger scale reworks of our nav, which ended up breaking a few links. They should all have redirects, but thought I'd go ahead and fix up some of your links in case things get funky on our end again.
On another note, if y'all ever have any questions or ideas about how we can work together PLEASE feel free to reach out!

Fix broken OP links

---

src/pages/_app.tsx

Update meta tags

---

next.config.mjs

find excel on linear task description.

fixed broken URL based on excel file shared

---

src/pages/mini-apps/reference/api.mdx

Adds a note that debug URLs provided by the endpoint typically expire after 1 hour.

feat: [DEV-1469] Add note about debug URL expiration

---

src/components/QrTest.tsx
src/pages/mini-apps/quick-start/commands.mdx
src/pages/mini-apps/quick-start/installing.mdx

Add docs examples

---

src/pages/world-id/id/cloud.mdx
src/pages/world-id/id/on-chain.mdx

source:
* https://github.com/worldcoin/developer-portal/blob/880479033cd11c596811555056cb8fac6c1a5f14/web/api/v2/verify/index.ts#L39
* other source is our smart contracts (see slack)

add notes on proof validity window

---

src/components/Navigation.tsx
src/pages/mini-apps/more/developer-rewards-pilot.mdx
src/pages/mini-apps/quick-start/testing.mdx

developer rewards pilot

---

src/pages/mini-apps/virality/virality.mdx

mention metatag images and explain the logic a bit

mention metatags

---

src/components/Navigation.tsx
src/pages/mini-apps/commands/get-permissions.mdx
src/pages/mini-apps/commands/request-permission.mdx
src/pages/mini-apps/reference/microphone.mdx

Microphone Docs

---

src/pages/mini-apps/reference/api.mdx

Document an existing endpoint that was requested a few times during hackathons etc.

document create-action

---

src/components/Navigation.tsx
src/pages/mini-apps/sharing/quick-actions.mdx

Also removed eggs vault and world chat QA

Renamed quick actions tab to sharing
